### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by rpietro** [ropensci/ropensciDemos#3]
>   install_github("ropensciDemos")
> Installing github repo(s) ropensciDemos/master from hadley
> Downloading ropensciDemos.zip from https://github.com/hadley/ropensciDemos/archive/master.zip
> Error: client error: (406) Not Acceptable
> 
> install_github("ropensci")
> Installing github repo(s) ropensci/master from hadley
> Downloading ropensci.zip from https://github.com/hadley/ropensci/archive/master.zip
> Error: client error: (406) Not Acceptable

**Comment by sckott** [comment]
Hi @rpietro , Try this:

``` coffee
install_github("ropensciDemos", "ropensci")
```

**Comment by karthik** [comment]
Right, also @rpietro please note that this isn't ready. We just ran a round of workshops and are going to move all that material in here so it would be a one step easy install. Can drop you a note once that's ready (likely this week).

**Comment by sckott** [comment]
Woops, sorry, what Karthik said

**Comment by karthik** [comment]
But @SChamberlain is right. Since Hadley Wickham wrote the package, the default username is his. So if you leave out the username it will look under his account. The code Scott provided is what you'll need to install once this is ready.

**Comment by rpietro** [comment]
Thanks Karthik
